
-- CREATING SCHEMA ----------------------------

DROP SCHEMA IF EXISTS BIKE_SERVICE_SLOT_BOOKING;
CREATE SCHEMA  BIKE_SERVICE_SLOT_BOOKING;
USE  BIKE_SERVICE_SLOT_BOOKING;

-- ---------------------------------------------------------------------------------

--  ------------------------------CUSTOMER DETAILS TABLE---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS BIKE_SERVICE_SLOT_BOOKING.CUSTOMER_DETAILS(CUSTOMER_ID INT PRIMARY KEY AUTO_INCREMENT,FIRST_NAME VARCHAR(50) NOT NULL,
LAST_NAME VARCHAR(50) NOT NULL,MOBILE_NO VARCHAR(10) NOT NULL, EMAIL VARCHAR(25) NOT NULL,PASSWORD VARCHAR(20) NOT NULL);

--  ------------------------------SERVICE PROVIDER TABLE---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS BIKE_SERVICE_SLOT_BOOKING.SERVICE_PROVIDER_DETAILS(SERVICE_PROVIDER_ID INT PRIMARY KEY AUTO_INCREMENT,NAME VARCHAR(50) NOT NULL,
CONTACT_NO VARCHAR(10) NOT NULL,CITY VARCHAR(255) NOT NULL,LANDMARK VARCHAR(255),EMAIL VARCHAR(200) NOT NULL,PASSWORD VARCHAR(20) NOT NULL );

--  ------------------------------OPERATIONS TABLE---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS BIKE_SERVICE_SLOT_BOOKING.OPERATIONS(OPERATIONS_ID INT PRIMARY KEY AUTO_INCREMENT ,NAME VARCHAR(250) NOT NULL,
COST decimal(8,2));

--  ------------------------------PLAN TABLE---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS BIKE_SERVICE_SLOT_BOOKING.SERVICE_PLAN(PLAN_ID INT PRIMARY KEY,NAME VARCHAR(200) NOT NULL,
DESCRIPTION VARCHAR(255) NOT NULL,IMAGE VARCHAR(200),COST FLOAT,SERVICE_PROVIDER_ID INT,
CONSTRAINT FK_SERVICE_PROVIDER_ID FOREIGN KEY(SERVICE_PROVIDER_ID) REFERENCES SERVICE_PROVIDER_DETAILS(SERVICE_PROVIDER_ID) );

--  ------------------------------PLAN_OPERATIONS MAPPING TABLE---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS BIKE_SERVICE_SLOT_BOOKING.OPERATIONS_PLAN_MAPPING(OPERATIONS_ID INT ,PLAN_ID INT,  
CONSTRAINT FK_OPERTAIONS FOREIGN KEY(OPERATIONS_ID) REFERENCES OPERATIONS(OPERATIONS_ID),
CONSTRAINT FK_PLAN FOREIGN KEY(PLAN_ID) REFERENCES SERVICE_PLAN(PLAN_ID));

--  ------------------------------SLOT TABLE---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS BIKE_SERVICE_SLOT_BOOKING.SLOT(SLOT_ID INT PRIMARY KEY,SLOT_DATE DATE, TOTAL_SLOT INT,MORNING_SLOT INT,
AFTERNOON_SLOT INT ,REMAINING_SLOT INT GENERATED ALWAYS AS(MORNING_SLOT+AFTERNOON_SLOT),SERVICE_PROVIDER_ID INT,
CONSTRAINT FK_SLOT FOREIGN KEY(SERVICE_PROVIDER_ID) REFERENCES SERVICE_PROVIDER_DETAILS(SERVICE_PROVIDER_ID));

--  ------------------------------BOOKING_DETAILS TABLE---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS  BIKE_SERVICE_SLOT_BOOKING.BOOKING_DETAILS(BOOKING_ID INT PRIMARY KEY AUTO_INCREMENT, VECHILE_NO VARCHAR(10) NOT NULL,
MODEL_NO VARCHAR(100),BOOKING_SLOT VARCHAR(20),TOTAL_COST FLOAT,PREPAID_COST FLOAT,
REMAINING_COST FLOAT GENERATED ALWAYS AS (TOTAL_COST-PREPAID_COST),PLAN_ID INT NOT NULL,
CUSTOMER_ID INT,SERVICE_PROVIDER_ID INT,
CONSTRAINT FK_USER FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER_DETAILS(CUSTOMER_ID),
CONSTRAINT FK_plantable FOREIGN KEY(PLAN_ID) REFERENCES SERVICE_PLAN(PLAN_ID),
CONSTRAINT FK_servierprovider FOREIGN KEY(SERVICE_PROVIDER_ID) REFERENCES SERVICE_PROVIDER_DETAILS(SERVICE_PROVIDER_ID));







